apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chutes-job-network-policy
spec:
  podSelector:
    matchLabels:
      chutes/chute: "true"
      chutes/job: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    # DNS resolution
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # Allow any egress to non-private IP ranges
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 169.254.0.0/16
              - 100.64.0.0/10
    
    # Kubernetes API server access (default namespace, any TCP port)
    - to:
        - namespaceSelector:
            matchLabels:
              name: default
      ports:
        - protocol: TCP
