createPasswords: false  # XXX only ever set to true one time (first time)!!!

cache:
  max_age_days: 30
  max_size_gb: 500
  overrides:
# Add any per-node cache size (in GB) overrides here, e.g.:
#    chutes-miner-gpu-0: 1000
#    chutes-miner-gpu-1: 1500

validators:
  defaultRegistry: registry.chutes.ai
  defaultApi: https://api.chutes.ai
  supported:
    - hotkey: 5GYgtw3J9aXaymosqYCcxX2EpgnRHHJUszbd1zSN9dEwVSEh
      registry: registry.chutes.ai
      api: https://api.chutes.ai
      socket: wss://ws.chutes.ai

minerApi:
  image: parachutes/miner:latest
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "4Gi"
  service:
    type: NodePort
    nodePort: 32000
    port: 8000
    targetPort: 8000
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values: ["true"]
  tolerations: []

gepetto:
  image: parachutes/miner:latest
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "4Gi"
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values: ["true"]
  tolerations: []

postgres:
  image: postgres:16
  imagePullPolicy: IfNotPresent
  persistence:
    enabled: true
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "4Gi"
  database:
    name: chutes
    user: chutes
    passwordKey: "postgres-password"
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - chutes-miner-cpu-0
  tolerations: []

redis:
  image: redis:7
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  nodeSelector: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: NotIn
            values: ["true"]
  tolerations: []
  resources:
    requests:
      cpu: "256m"
      memory: "256Mi"
    limits:
      cpu: 1
      memory: 1Gi
  service:
    type: ClusterIP
    port: 6379
  password:
    passwordKey: "redis-password"
  config:
    customArgs: []

registry:
  image: nginx:1.27
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000
    # BE SURE THIS MATCHES registry_port IN ANSIBLE!
    nodePort: 30500
  nodeSelector:
    nvidia.com/gpu.present: "true"
  config:
    workerProcesses: 1
    workerConnections: 1024
    keepaliveTimeout: 65
    clientMaxBodySize: "0"
    validators:
      allowedHosts:
        - "registry.chutes.ai"
      defaultUpstream: "registry.chutes.ai"

auditExporter:
  image: parachutes/miner:latest
  nodeSelector:
    kubernetes.io/hostname: chutes-miner-cpu-0

failedChuteCleanup:
  image: bitnami/kubectl:latest
  nodeSelector:
    kubernetes.io/hostname: chutes-miner-cpu-0
