all:
  vars:
    # This is your SSH public key, e.g. cat ~/.ssh/id_rsa.pub
    ssh_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2tDDwwyJDuBmzg2KM+6nrnJ5c12VgMSA05KEcxVm/aSNC7oBC6qhlR5NIw4uArO+6avP5yYpBHZp9zA5R6WVYkfh4VC2lhTee1CU/VuP4s+PjmhMNf+GCMuKzB4Xi9V0wu9mtcbAoDWPB7/Md+RT7fOTVlc1ilvMC/50QQIQKzNzP3O3NHAS2vhQOeH0SV/h9wStWrFWFBeE5fq+mbc6mTWrQeuApkfLvbSRV+xToUi3cdsSyZi8RvB9mVTfaBOTdxDC+ZZHlr5igI0CJjW4IHD9HrMZWHqkCqcqmplCQVUNpfUOhdcYRdslyB76lHmdOm0SWI5N+fEQLwRL2DBpnKpmmRCUXmYlH7IdofZll+4f5jO/B3GijC+4ckENC2qCWz0lif0H+2R017Xmbx1ETjKdE6x+bNJk+RjcyBbaeu0c5XXFXI4OzTWgEdTcc0CdbXzvwnBddmgXCaTryhjYf/O/HTosBWXBRc3x1IiU29SPEt4KpwI37aIM66oG6b5c= root@Miner-Controller"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEsuS135lzjVvlH2iNrKz23lDFr7b686xs4d2HINP2glFPmgkgx1D6Dqwisb1UbhWHZmUUzRxXeNlE8fiaO0TXN/C0dsdUxgopnQRyakcA+gfJqqb38Syx8eqdC7mQy9ygOf763dWm6d/SYZ8WgNWLldk4QF9DiZOW9K22DMtY4/1Cqe/YE/WGpOMVr9T9BwvmOjarjWp2OPbx6RVlSOd735Mze5X+cJ9QqdLaisCiSoJ3j9S6dulcxm+7ghPfATvxlJyZWSrRrVqnmV45lPbeuUHlIEyuK1PK2MS6NtUP03ZhdRYJQKZLECpR5xAO/BliOtDdRornvHV1gutYD8/n3IS8sRVzYPvN9DuOhzBnBQUgciu2++R8zMfdVoH7mSbsE8u++vMcBk3UJ1Op0Ct+trl2bsnue96cAnoiII08JKwAaczD5uZIGhdkGV8zKnChNCjzCxP0i4PV/MYW04eWmH+E8G81zq4ZsvrvPYmilBbRrkwHvvbPba3SSb2F2As= shenlan@shenlandeMacBook-Air-2.local"
    # The username you want to use to login to those machines (and your public key will be added to).
    user: root
    # The initial username to login with, for fresh nodes that may not have your username setup.
    ansible_user: root
    # The default validator each GPU worker node will be assigned to.
    validator: 5GYgtw3J9aXaymosqYCcxX2EpgnRHHJUszbd1zSN9dEwVSEh
    # By default, no nodes are the primary (CPU node running all the apps, wireguard, etc.) Override this flag exactly once below.
    is_primary: false
    # We assume GPU is enabled on all nodes, but of course you need to disable this for the CPU nodes below.
    gpu_enabled: true
    # The port you'll be using for the registry proxy, MUST MATCH chart/values.yaml registry.service.nodePort!
    registry_port: 30500
    # SSH sometimes just hangs without this...
    ansible_ssh_common_args: '-o ControlPath=none'
    # SSH retries...
    ansible_ssh_retries: 3
    # Ubuntu major/minor version.
    ubuntu_major: "22"
    ubuntu_minor: "04"
    # CUDA version - leave as-is unless using h200s, in which case either use 12-5 or skip_cuda: true (if provider already pre-installed drivers)
    cuda_version: "12-9"
    # NVIDA GPU drivers - leave as-is unless using h200s, in which case it would be 555
    nvidia_version: "575"
    # Flag to skip the cuda install entirely, if the provider already has cuda 12.x+ installed (note some chutes will not work unless 12.6+)
    skip_cuda: false
    # Flag to enable/disable IPv6. Some hosts may require IPv6 to be on.
    ipv6_enabled: true
    # Default MTU
    wireguard_mtu: 1380

  hosts:
    # This would be the main node, which runs postgres, redis, gepetto, etc.
    chutes-miner-cpu-0:
      ansible_host: 172.29.133.135
      external_ip: 8.219.223.71
      wireguard_ip: 192.168.0.1
      gpu_enabled: false
      is_primary: true

    chutes-miner-gpu-1:
      ansible_host: 172.29.133.134
      external_ip: 47.236.131.91
      wireguard_ip: 192.168.0.3

    chutes-miner-gpu-2:
      ansible_host: 172.29.133.136
      external_ip: 8.222.214.54
      wireguard_ip: 192.168.0.4
